name: ci
on: [push, pull_request]
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Terraform fmt
        run: terraform -chdir=02-infra/org/terraform fmt -check || true
      - name: Terraform validate
        run: terraform -chdir=02-infra/org/terraform validate || true
