name: ml-monitor
on:
  push:
  pull_request:
  schedule:
    - cron: "0 6 * * *"   

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          # minimal deps for demo checks
          echo "numpy==1.26.4" >> requirements.txt
          echo "pytest" >> requirements.txt
          pip install -r requirements.txt
      - name: Run monitoring checks
        run: |
          python 04-ml/monitoring/run_checks.py
      - name: Upload metrics.jsonl (artifact)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: monitoring-metrics
          path: 04-ml/monitoring/metrics.jsonl
