name: secret-scan
on: [push, pull_request]

permissions:
  contents: read
  security-events: write

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: detect --redact --source . --report-format sarif --report-path gitleaks.sarif
        continue-on-error: true

      - name: Ensure SARIF exists when clean
        run: |
          if [ ! -s gitleaks.sarif ]; then
            cat > gitleaks.sarif <<'JSON'
            {
              "version": "2.1.0",
              "runs": [
                {
                  "tool": {
                    "driver": {
                      "name": "gitleaks",
                      "informationUri": "https://github.com/gitleaks/gitleaks"
                    }
                  },
                  "results": []
                }
              ]
            }
            JSON
          fi

      - name: Upload SARIF to code scanning
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: gitleaks.sarif
